### ISSUE TITLE
Error when trying to "Empty Queue" with over 100 000 messages

### ISSUE THREAD

**Issue by qila24** [jmstoolbox/jmstoolbox#11]
## Specifications
- JMSToolBox version: 4.4.1
- OS (Name, version, 32/64bits): Windows 7 Enterprise/64 bits
- Q provider (kind, version) : MQ 9

## Expected Behavior
Delete all message in the queue

## Actual Behavior
I get a first error message (see JMSToolBoxError1).
When I close that message, I get a second error (See JMSToolBoxError2).

![jmstoolboxerror1](https://user-images.githubusercontent.com/39098023/39772195-90acd958-52c2-11e8-85d7-f077117f5b1e.png)
![jmstoolboxerror2](https://user-images.githubusercontent.com/39098023/39772201-9323af22-52c2-11e8-9ecd-7094426a1f8c.png)

## Steps to Reproduce the Problem

  1. Have over 100 000 messages in a queue
  2. right-click on the Q and select menu "Empty Queue"
  3. Wait for a while...

## Logs
Eventually, attach the log files which are `"<user>\.jtb\JMSToolBox\jmstoolbox.log"` and `"<user>\.jtb\.metadata\.log"`    
They can be exported directly from JMStoolBox: Menu "Help" > "Export JMSToolBox log files..."

**Comment by titou10titou10** [comment]
HI,
Thanks for using JMSToolBox
This is not a JTB bug
This happens because your IBM MQ does not allow to process this number of messages (> 100.000 in your case) in one unit of work (UOW)
To solve the problem, either select less messages in JTB at once, of change the MQ Manager configuration to augment the number of messages that can be process in one unit of work ("Max Uncommited messages" aka parametres `"MQCMIT"` or `"MQDISC"`)
