### ISSUE TITLE
No queues are visible when session is opened on an embedded Apache Active MQ

### ISSUE THREAD

**Issue by marcoaltieri** [jmstoolbox/jmstoolbox#17]
## Specifications
- JMSToolBox version: v4.10.0
- OS (Name, version, 32/64bits): Ubuntu Xenial 64bits
- Q provider (kind, version) : Embedded ActiveMQ 5.14.5 (started using Spring Boot 1.5.13.RELEASE)

## Expected Behavior
In the running ActiveMQ broker there are a couple of queues. 
I can see them using jconsole and the connection string:
service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi
Using jconsole, I can send messages to the existing queues as well.

I am expecting to see the same queues in JMSToolbox.

## Actual Behavior
After opening a connection, I do not see any queue.
There is an exception in the .log file. See attachments.

## Steps to Reproduce the Problem

  1. Start JMSToolbox
  2. Define a new session with: 
         queue manager: Apache Active MQ
         hostname: localhost
         port: 1099
  3. Open the session.
 
I can see the folder "Queues" and "Topics" but no children.
[jmstoolbox.log](https://github.com/jmstoolbox/jmstoolbox/files/2196046/jmstoolbox.log)
[log.log](https://github.com/jmstoolbox/jmstoolbox/files/2196047/log.log)

**Comment by titou10titou10** [comment]
I tested it here with this code that starts and embedded ActiveMQ v5.15.4 broker, create one queue and one topic and it works with JMSToolBox...

    BrokerService broker = new BrokerService();
    broker.addConnector("tcp://localhost:61616");
    broker.setUseJmx(true);
    ActiveMQDestination q = ActiveMQDestination.createDestination("testQueue", ActiveMQDestination.QUEUE_TYPE);
    ActiveMQDestination t = ActiveMQDestination.createDestination("testTopic", ActiveMQDestination.TOPIC_TYPE);
    broker.setDestinations(new ActiveMQDestination[] { q, t });
    broker.start();

![activemq_embedded](https://user-images.githubusercontent.com/15241034/42759821-488e83ac-88d6-11e8-8ab1-cb332f77a5ba.png)

**Comment by marcoaltieri** [comment]
This is what I can see in jconsole.
![image](https://user-images.githubusercontent.com/5622790/42796636-3170bdcc-8983-11e8-9765-6aa7fe3f5023.png)

**Comment by titou10titou10** [comment]
Normally with recent versions of ActiveMQ, the Queues are listed in JMX as:    
 `org.apache.activemq:type=Broker,brokerName="<name>",destinationType=Queue,destinationName=<Queue name>`   

In your case they are named:
`localhost:type=Broker,brokerName="<name>",destinationType=Queue,destinationName=<Queue name>`   

This very strange and this is why JTB does not find them as it is looking for `org.apache.activemq:type=Broker,{...}` entries.    
I also see a "`Tomcat`" entry in your JMX tree.. Could you tell me how the embedded ActiveMQ instance is created? Some code maybe?
Below the JConsole print screen of my tests with an embedded ActiveMQ from the code I posted earlier   
 
![jconsole](https://user-images.githubusercontent.com/15241034/42834238-96f20b24-89c4-11e8-9422-f8ef00033d4f.png)

**Comment by marcoaltieri** [comment]
Please find here the code that starts the embedded activemq.

https://github.com/marcoaltieri/jmstoolboxtest

**Comment by titou10titou10** [comment]
I can see that in the`"activemq.xml"`file that the`'useJmx="true"'`attribute on the`"broker"`tag is not there.  Strange because the JMX MBeans seems to be activated anyway. Maybe this why the `"jmxDomainName"`does not default to`"org.apache.activemq"`as said in the doc but is set to`"localhost"`in your case

The code changes i made for v4.11.0 should allow JTB to discover the destinations whatever the JMX domain name is.
Could you remove the`"jmxDomainName"`attribute in your config file and test with JTB v4.11.0 to confirm it works even with a JMX domain name set to something different than`"org.apache.activemq"`?
Thanks !

Some links:
[JMSToolBox setup for ActiveMQ ](https://github.com/jmstoolbox/jmstoolbox/wiki/2.5-Setup-for-Apache-ActiveMQ)
[ActiveMQ Doc on how to activate JMX](http://activemq.apache.org/jmx.html)
