### ISSUE TITLE
Export/Import messages in bulk

### ISSUE THREAD

**Issue by heatzync** [jmstoolbox/jmstoolbox#52]
In the "Browse Queue" window it should be possible to export all the messages in "view", i.e. either all the messages or only the messages that match the filters, to be exported to a file (or multiple files on disk).

It should then be possible to import these messages from disk into another queue.

Edit for clarity: I noticed that drag and drop works very nicely for multiple messages, but sometimes I need to save the messages from one environment (behind a firewall etc.) and test them in another environment at a later stage.

**Comment by titou10titou10** [comment]
it is already possible to select multiple messages and then "export as template..."
This will export the selected messages that you can "import" elsewhere, ie in another QM/Queue
Are you asking for something else?

**Comment by heatzync** [comment]
Hi @titou10titou10.

I don't see the "Export as template..." option when right clicking after selecting multiple messages.

I only see "Save as Template..." when I right click on a single message:
![image](https://user-images.githubusercontent.com/1142791/56357357-d7564c80-61db-11e9-991c-2afd96802e25.png)

Here is what I see when right clicking after multiple messages were selected:
![image](https://user-images.githubusercontent.com/1142791/56357401-f2c15780-61db-11e9-8ca4-86637878faaf.png)

I am using v5.1.0 (2019-02-22 13:23).

**Comment by titou10titou10** [comment]
OK
This contextual menu is not available for you because you select on or more messages of kind`"ObjectMessage"`   
There are a lot of restrictions on this kind of messages in JTB and exporting/importing is one of them.
The reason is because JTB can not import back such messages. In order to "post" a message of kind`"ObjectMessage"` JMS reauires the producer to have the implementation class in its classpath.    
This is a long standing restriction that has to be addressed to make JTB more `"ObjectMessage"`friendly     
The problem is that I don't know how to solve the problem because of the complexity of the eclipse/OSGI/plugin classpath behavior and how to upload/manage the jars with the`"ObjectMessage"` implementations classes with regards with JTB classpath

**Comment by heatzync** [comment]
Hi @titou10titou10.

Thank you for the quick response.

I understand your explanation about the Object messages.

I tried the same with multiple selected Text messages and I was able to "Export payload..." and "Export as Template..." one-by-one. With one-by-one I mean that the application prompts for a file name for each individual message.

Would it be possible to export all messages into a single (bulk) file using a JMSToolBox specific format? It should then also be able to import the individual messages from the (bulk) file that contains this JMSToolBox specific format.

**Comment by Chry007** [comment]
Is this still not available?

**Comment by cabellouarkbluecross** [comment]
Just adding on that this would still be a useful feature to have.

**Comment by titou10titou10** [comment]
> Is this still not available?

PR are welcome...
