### ISSUE TITLE
Authentification error 2035 when MQis configured to login with a userid and no password

### ISSUE THREAD

**Issue by jfacp** [jmstoolbox/jmstoolbox#90]
## Specifications
- JMSToolBox version: 3.12.0
- OS (Name, version, 32/64bits): Windows 64bits
- Q provider (kind, version) : IBM MQ

## Expected Behavior
I am trying to connect to a IBM MQ session, with an id but no password.

## Actual Behavior
When I try to connect to the Session, I get the following error : 
com.ibm.mq.MQException: MQException : MQJE001: Code achèvement '2', Motif '2035'

It seems that the connection is not possible without a password. I know that MQJExplorer for exemple allows that type of connection. Is there a parameter I can change to be able to connect with JMSToolBox ? (It used to work one year ago, I don't know why it doesn't work anymore.)

Thank you !

## Steps to Reproduce the Problem

  1. Creating a session with Host, Port, User, QueueManager and Channel, but no Password
  2. Try to connect

**Comment by titou10titou10** [comment]
It is supposed to work. I'll check the code later

**Comment by titou10titou10** [comment]
I can confirm that JTB allows toi connect to IBMMQ without a password
Q: Is your server configured for that? 
Did you connect from another tool (ie MQ Explorer or other client app) with the same server/channel etc without a password?

**Comment by jfacp** [comment]
Hello,

I have to admit that I don't know if the server is well configured. I have tried to connect via MQJExplorer and it worked well with the Queue Manager Name, the Host and the Port only. 
The version of the Unix MQSeries I am trying to connect to is the 7.5.0, and I am using the 9.0.4.0 version of com.ibm.mq.allclient.jar.
Thank you for your help

**Comment by titou10titou10** [comment]
Could you try JTB with the mq.allclient jar that corresponds to the server version? 
Many security enhancements have been done in later mq client jars and they may be responsible of the problem
https://www.ibm.com/support/pages/withdrawn-mqc75-websphere-mq-v75-clients#1

**Comment by jfacp** [comment]
Hello,

Sorry for the response time.
I tried the mq.allclient that corresponds to the server version, but it still send the same error.
I also upgraded JTB to the earliest version with no results. 
Could it be a problem with the channel ? Is it possible to connect without filling in the Channel ?

Thank you for your help

**Comment by jfacp** [comment]
(P.S :  
I found these two topics : 
https://www.ibm.com/support/pages/node/964948
https://sourceforge.net/p/jmstoolbox/features/11/

I tried to add a -Duser.name in the JMSToolBox.ini, but it still send me the same error.)

**Comment by borramTAS** [comment]
I have a similar problem, with or without password I receive the same message:

```
com.ibm.mq.MQException: MQJE001: Completion Code '2', Reason '2035'.
MQJE001: Completion Code '2', Reason '2035'.
```

**Comment by titou10titou10** [comment]
@borramTAS same questions as before:

- Is your server/channel configured for login without password? 
- Did you connect from another tool (ie MQ Explorer or other client app) with the same server/channel etc without a password?
- What is the version of the MQ server you are trying to connect to?
- What version of com.ibm.mq.allclient.jar are you using?

**Comment by borramTAS** [comment]
Hi @titou10titou10,

- Is your server/channel configured for login without password? --> The server/channel is configured for login with password, other server that is configured for login without password (JMSToolBox) works correctly.
- Did you connect from another tool (ie MQ Explorer or other client app) with the same server/channel etc without a password? --> MQ Explorer works correctly with or without password works correctly in accordance with the server/channel configuration.
- What is the version of the MQ server you are trying to connect to? --> MQ Server version: 9.1.5.0 (Docker)
- What version of com.ibm.mq.allclient.jar are you using? --> 9.1.5.0

**Comment by sulfatchlorid** [comment]
We see the same problem and opened a service request at IBM. 
The result is that JMSTOOLBOX opens another connection for queue browsing without authentication and that's why you cannot browse messages in a queue. We have user/password authentication enabled.
I guess for browsing JMSTOOLBOX does not pass the given credentials but i am not sure.

**Comment by felgoe** [comment]
Are there any updates on the issue? I'm seeing the same problem using the 9.2.3.0 version of the IBM MQ Docker image and the 9.2.3.0 version of com.ibm.mq.allclient jar.

**Comment by felgoe** [comment]
Hi @titou10titou10 

Sorry if the conveyed information was not clear. My comment was referencing the latest comment by @borramTAS .

To answer your questions:

* I'm using the default configuration of IBM MQ developer Docker image. (v9.2.3.0)
* The server channel is configured for login with userId and password
* Login and browse with MQ Explorer works as expected using userId and password
* JTB is configured with com.ibm.mq.allclient.jar v9.2.3.0 (I tried other versions as well w/o success)
* Login with JTB using userId and password results in the aforementionen RC2035

**Comment by titou10titou10** [comment]
@felgoe you should then open another issue.     
*"MQJE001: Completion Code '2', Reason '2035'"* is a very "generic" error in MQ. You should activate/check the logs on the server side to see what the exact problem is

**Comment by sulfatchlorid** [comment]
2035 is an authentication error, not a generic error. 
The reason for this error is already explained in my previous post and it's in the code of jmstoolbox. 
You connect to MQ with credentials but after connecting you try to browse Queues with another unauthorized connection without credentials and that fails so we dropped Jmstoolbox and used MQ Admin Tool instead.
This authentication problem has been analyzed by IBM but you can of course believe what you want.

**Comment by titou10titou10** [comment]
> 2035 is an authentication error, not a generic error.

I meant this error covers many different problems related to authentication, this was the reason on the quote around the "generic" word (Did you see them?)

> The reason for this error is already explained in my previous post and it's in the code of JMSToolBox.

Yep. This issue is about connecting to JTB with a userid and no password... In one post you write  that *"We have user/password authentication enabled"* and in another *"We see the same problem"* . so the question in my last post and the feeling that it seems you are hijacking this issue

> You connect to MQ with credentials but after connecting you try to browse Queues with another unauthorized connection without credentials and that fails so we dropped Jmstoolbox and used MQ Admin Tool instead.

For MQ Explorer, that's great you find a product that fulfills your needs.
I *"personally"* don't' connect to *"your"* server...lol, or if it happens, it is against my will, I swear..lol
I'm sure you already checked the code of JTB, so you've certainly seen that JMSToolBox indeed uses 2 connections, one for administration tasks (eg get the Q list..) and one to get a JMS connection

https://github.com/jmstoolbox/jmstoolbox/blob/b42dfedf71abb7d86f0e74c9c241db9d6d69122c/org.titou10.jtb.qm.ibmmq/src/org/titou10/jtb/qm/ibmmq/MQQManager.java#L353-L356

https://github.com/jmstoolbox/jmstoolbox/blob/b42dfedf71abb7d86f0e74c9c241db9d6d69122c/org.titou10.jtb.qm.ibmmq/src/org/titou10/jtb/qm/ibmmq/MQQManager.java#L416

You can see in the code how the userid/passwords are handled
JTB can alsso open more JMS connections, eg if you are using scripts or REST or some other features

> This authentication problem has been analyzed by IBM but you can of course believe what you want.

@sulfatchlorid wow. lol. Hopefully you didn't pay much for JMSToolBox, few !

To conclude, tens of people use JMSToolBox successfully to connect to MQ series (various versions) in different context, including many employees at my own company, some with userid/pwd, some with userid only, some with client certs etc, with so the problem you are facing does not seem to be the rule even if obviously JTB is way from being bug free.  Your participation (Pull Requests, code review,...) is always welcome of course, feel free to review the code

Finally good luck in *your* usage of free open source software and MQ Explorer is of course a brilliant, well supported product, so you're safe with it

Denis, author of JMSToolBox
