### ISSUE TITLE
Support Azure Service Bus as a JMS provider

### ISSUE THREAD

**Issue by anqyan** [jmstoolbox/jmstoolbox#94]
## Specifications
- JMSToolBox version:
- OS (Name, version, 32/64bits):
- Q provider (kind, version) : Azure Service Bus https://azure.microsoft.com/en-us/services/service-bus/

## Expected Behavior
To add Azure Service Bus as a queue provider among https://github.com/jmstoolbox/jmstoolbox/wiki#setup-per-q-provider

## Actual Behavior
I was reading through https://github.com/jmstoolbox/jmstoolbox/issues/81 to get some clues but had difficulty start development. My dev environment is setup though.

To create JMS connections or get queues/topics, Microsoft provides a Maven package https://search.maven.org/artifact/com.microsoft.azure/azure-servicebus-jms. So I think we have the basics. I assume I have to create a module with prefix `org.titou10.jtb.qm.` and implement `QManager` class. But I'm not sure how to include the dependency `azure-servicebus-jms` in the project and import to my implementation. Could you elaborate how I can include that package as a dependency for the plugin development? So that I'll be able to create a pull request for this feature.

**Comment by titou10titou10** [comment]
In order to add a new Queue Manager, yes you need to create a new plugin project and extends the org.titou10.jtb.core.QManagerProvider extensions point from core. This Will lead to create a class that implements QManager

As for including externals jar, if they are free of usage rights, currently the best way for now is to download/put them into a "lib" sub dir and reference them in the plugin. Check the artemis or activemq plugins. This is a kind of OSGI anti-pattern but I need to find time to implement a better more OSGI friendly way

BUT before that, the QM must provide a way to connect to the server and provide an API to retrieve the list of the destination. This is not part of the JMS standard 

Then when JTB has the list of destination, it only uses the JMS API and it seems that the [library provided by MS](https://github.com/Azure/azure-service-bus/blob/master/samples/Java/qpid-jms-client/JmsQueueQuickstart/readme.md) for Azure Service Bus has a few unsupported methods that are required by JTB. At least`"createBrowser()", "createQueue()"`etc

And I don't see any reference to JMS in the [new github project for azure service bus](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/servicebus) event if [this article](https://azure.microsoft.com/en-us/blog/announcing-preview-of-java-message-service-2-over-amqp-on-azure-service-bus/) says it is available

Anyway, if you want to work on that, I can easaly create the plugin for you in a branch in JTB

**Comment by anqyan** [comment]
Hey @titou10titou10 , thanks for the quick response. 
Yes please create a skeleton plugin in a branch as a starting point for me. It will be super helpful!
Azure Service Bus is about to fully launch JMS 2.0 support. This documentation is more up-to-date: https://docs.microsoft.com/en-us/azure/service-bus-messaging/how-to-use-java-message-service-20

**Comment by titou10titou10** [comment]
new branch with skeleton QM implementation class for Azure Service Bus pushed

**Comment by heatzync** [comment]
Hi @titou10titou10 and @anqyan.

Thank you for adding the Azure ServiceBus support.

Do you perhaps have an example of how to connect a session? I'm setting the connectionString property as obtained from Azure Portal, but nothing happens when I try to connect.

Alternatively, I would also appreciate it if you added the details to the wiki page here:
https://github.com/jmstoolbox/jmstoolbox/wiki/2.14-Setup-for-Azure-SB

**Comment by anqyan** [comment]
@heatzync Only using a connection string to setup a session should be sufficient to connect. Does the connection string have Manage, Listen and List Claims?
@titou10titou10 I just deleted <user_home>/.jtb folder, downloaded release 5.9.0 and was not able to reproduce this issue on my end.

**Comment by heatzync** [comment]
@anqyan: Thank you for your response.

The Manage, Send and List claims do exist.

Your other comment about deleting `~/.jtb` pointed me towards the real log file in `~/.jtb/JMSToolBox/jmstoolbox.log`. I was previously looking in the installation folder.

I then found the following DEBUG messages in the logs:

> DEBUG [o.a.q.j.p.f.FailoverProvider] Request received error: Full JMS 2.0 parity over AMQP is a feature supported only by a Premium Messaging namespace. TrackingId:9f9cdeadbeef440edeadbeefa6d7d684_G8, SystemTracker:gateway7, Timestamp:2020-12-02T11:41:10 [condition = amqp:not-implemented]

I'm only using a Standard Messaging namespace for development.

**Comment by anqyan** [comment]
@heatzync I see. Are you using any JMS 2.0 features in your application? Standard tier Service Bus does support JMS but it's limited: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-java-how-to-use-jms-api-amqp 
@titou10titou10 I will add Service Bus Standard tier compatibility in the QM class to fix this.

**Comment by titou10titou10** [comment]
@anqyan you can not use the "old" JMS interface for Azure as tere are critical method non implemented. The doc has to specify that the Azure plugin requires the premium level of service

**Comment by anqyan** [comment]
@titou10titou10 Got it. I'll update related Wiki and docs then.
@heatzync Looks like you have to use a Premium tier Service Bus namespace in this case.

**Comment by anqyan** [comment]
@titou10titou10 Seems I don't have permission to directly push changes to the wiki and I couldn't find a way to fork the wiki...so I just put a draft for the wiki page here: https://gist.github.com/anqyan/7d6015758eecf16d93b734e0900493b1 please update the wiki when you have time, thanks.

**Comment by titou10titou10** [comment]
Done.
Thanks !
